services:
  tensorflow27remote:
    image: atilileri/tensorflow:tf27rem
    container_name: tf27rem
    user: root
    environment:
      MYUSERDATA: "${USER}"
    build:
      context: .
      dockerfile: Dockerfile.tensorflow27_rem
      args:
        mysampleargument: buildArgTest123
    ports:
      - "7776:22" # ssh
      - "7777:7777" # gdb server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
#      - /tmp/:/tmp/
      - /logs/:/logs/
      - /data/:/data/

  tensorboard:
    image: atilileri/tensorboard:brdTF27rem
    container_name: tbtf27
    user: root
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
#    stdin_open: true
#    entrypoint: /bin/bash
    build:
      context: .
      dockerfile: Dockerfile.tensorboard_tf27
    ports:
      - "6006:6006" # tb instance 1
      - "6007:6007" # tb instance 2
      - "6008:6008" # tb instance 3
      - "6009:6009" # tb instance 4
      - "6010:6010" # tb instance 5
    volumes:
#      - /tmp/:/tmp/
      - /logs/:/logs/
#      - /data/:/data/
